image: paradoxxxzero/python-node-yarn-postgresql

cache:
   key: "$CI_BUILD_REF_NAME"
   untracked: true

stages:
  - install
  - build
  - test

install:
  stage: install
  script:
    - make install

  artifacts:
    paths:
      - node_modules/
      - .env/

build:
  stage: build
  script: make build

  artifacts:
    paths:
      - gibolt/frontend/static/

lint:
  stage: test
  script: make lint

test:
  stage: test
  script: make check
