cache:
   key: "$CI_COMMIT_REF_NAME"
   untracked: true

stages:
  - install
  - build
  - test
  - deploy_test
  - deploy_prod

.artifacts: &artifacts_install
  artifacts:
    paths:
      - node_modules/
      - .env/
    
.artifacts: &artifacts_build
  artifacts:
    paths:
      - gibolt/frontend/static/
      - node_modules/
      - .env/
 

image: paradoxxxzero/python-node-yarn-postgresql:3.5-7.2-9.6

install3.5:
  stage: install
  script:
    - make install
  <<: *artifacts_install

build3.5:
  stage: build
  script: make build
  <<: *artifacts_build
  dependencies:
    - install3.5

lint3.5:
  stage: test
  script: make lint
  dependencies:
    - build3.5

test3.5:
  stage: test
  script: make check
  dependencies:
    - build3.5


.image: &image_latest
  image: paradoxxxzero/python-node-yarn-postgresql:3.6-7.5-9.6

install_latest:
  <<: *image_latest
  stage: install
  script:
    - make install
  <<: *artifacts_install

build_latest:
  <<: *image_latest
  stage: build
  script: make build
  <<: *artifacts_build
  dependencies:
    - install_latest

lint_latest:
  <<: *image_latest  
  stage: test
  script: make lint
  dependencies:
    - build_latest

test_latest:
  <<: *image_latest
  stage: test
  script: make check
  dependencies:
    - build_latest


.image: &image_deploy_jobs
  image: debian:latest
      
deploy_test:
  <<: *image_deploy_jobs
  stage: deploy_test
  before_script: 
    - "apt-get update && apt-get install -y jq curl"
  script:
    - "res_curl=`curl -m 3600 -H 'Content-Type: application/json' -X POST -d '{\"token\":\"\'\"$TOKEN\"\'\", \"url\":\"\'\"$CI_REPOSITORY_URL\"\'\", \"build_stage\":\"\'\"$CI_JOB_STAGE\"\'\", \"project_name\":\"\'\"$CI_PROJECT_NAME\"\'\", \"branch\":\"\'\"$CI_COMMIT_REF_NAME\"\'\"}' $GERALDINE/deploy | jq -r \'.success\'` && branch_name=`echo $CI_COMMIT_REF_NAME | tr -cd '[[:alnum:]]'` && get=`curl -s -o -I -w \"%{http_code}\" https://test-$CI_PROJECT_NAME-$branch_name.kozea.fr` && [[ $get = 302 || $get = 200 && $res_curl=0 ]] && exit_val=0 || exit_val=1 && exit $exit_val"
  dependencies: []


deploy_prod:
  <<: *image_deploy_jobs
  stage: deploy_prod
  before_script:
    - "apt-get update && apt-get install -y jq curl"
  script:
    - "res_curl=`curl -m 3600 -H 'Content-Type: application/json' -X POST -d '{\"token\":\"\'\"$TOKEN\"\'\", \"build_stage\":\"\'\"$CI_JOB_STAGE\"\'\", \"project_name\":\"\'\"$CI_PROJECT_NAME\"\'\", \"branch\":\"\'\"$CI_COMMIT_REF_NAME\"\'\"}' $GERALDINE/deploy | jq -r \'.success\'` && get=`curl -s -o -I -w \"%{http_code}\" https://gibolt.kozea.fr` && [[ $get = 302 || $get = 200 && $res_curl=0 ]] && exit_val=0 || exit_val=1 && exit $exit_val"
  dependencies: []
  only: 
    - master
