include:
  - remote: 'https://gitlab.com/Kozea/ci-master/raw/master/.variables-images.yml'
  - remote: 'https://gitlab.com/Kozea/ci-master/raw/master/.ci-install.yml'
  - remote: 'https://gitlab.com/Kozea/ci-master/raw/master/.ci-lint.yml'
  - remote: 'https://gitlab.com/Kozea/ci-master/raw/master/.ci-deploy-test.yml'
  - remote: 'https://gitlab.com/Kozea/ci-master/raw/master/.ci-deploy-prod.yml'
  
.image_test_jobs:
  image: kozea/python-node-yarn-postgresql:latest

stages:
  - install
  - test
  - deploy_test
  - deploy_prod

.artifacts: &artifacts
  artifacts:
    paths:
      - .venv/

install:
  <<: *artifacts
