variables:
  PYTHON_VERSION: python
  STAGING: y

stages:
  - install
  - build
  - test
  - deploy_test
  - deploy_prod

.artifacts: &artifacts_install
  artifacts:
    paths:
      - node_modules/
      - .venv/

.artifacts: &artifacts_build
  artifacts:
    paths:
      - lib/frontend/static/
      - node_modules/
      - .venv/


image: paradoxxxzero/python-node-yarn-postgresql:latest

install_latest:
  stage: install
  script:
    - pip install pipenv
    - make install
  <<: *artifacts_install

build_latest:
  stage: build
  script: make build
  <<: *artifacts_build
  dependencies:
    - install_latest

lint_latest:
  stage: test
  script:
    - pip install pipenv
    - make lint
  dependencies:
    - build_latest

test_latest:
  stage: test
  script:
    - pip install pipenv
    - make check
  dependencies:
    - build_latest


.image: &image_deploy_jobs
  image: debian:latest

deploy_test:
  <<: *image_deploy_jobs
  stage: deploy_test
  before_script:
    - 'apt-get update && apt-get install -y wget'
  script:
    - 'set -e'
    - 'branch_name=`echo $CI_COMMIT_REF_NAME | tr -cd "[[:alnum:]]"`'
    - 'url_test=https://test-$CI_PROJECT_NAME-$branch_name.kozea.fr'
    - 'output_file=/tmp/$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.log'
    - 'parameters="{\"job_id\":\"$CI_JOB_ID\", \"token\":\"$TOKEN\", \"url\":\"$CI_REPOSITORY_URL\", \"build_stage\":\"$CI_JOB_STAGE\", \"project_name\":\"$CI_PROJECT_NAME\", \"branch\":\"$CI_COMMIT_REF_NAME\", \"commit_sha\":\"$CI_COMMIT_SHA\", \"url_test\":\"$url_test\"}"'
    - 'swget="wget --no-verbose --content-on-error -O-"'
    - '$swget --header="Content-Type:application/json" --post-data="""$parameters""" $JUNKRAT | tee $output_file && [[ $(tail -n1 $output_file) == "Success" ]]'
    - '$swget $url_test'
  dependencies: []

deploy_prod:
  <<: *image_deploy_jobs
  stage: deploy_prod
  before_script:
    - 'apt-get update && apt-get install -y wget'
  script:
    - 'set -e'
    - 'output_file=/tmp/$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.log'
    - 'parameters="{\"job_id\":\"$CI_JOB_ID\", \"token\":\"$TOKEN\", \"build_stage\":\"$CI_JOB_STAGE\", \"project_name\":\"$CI_PROJECT_NAME\", \"branch\":\"$CI_COMMIT_REF_NAME\"}"'
    - 'swget="wget --no-verbose --content-on-error -O-"'
    - '$swget --header="Content-Type:application/json" --post-data="""$parameters""" $JUNKRAT | tee $output_file && [[ $(tail -n1 $output_file) == "Success" ]]'
    - '$swget https://gibolt.kozea.fr'
  dependencies: []
  only:
    - master
