variables:
  PYTHON_VERSION: python
  STAGING: y

stages:
  - install
  - build
  - test
  - deploy_test
  - deploy_prod

.artifacts: &artifacts_install
  artifacts:
    paths:
      - node_modules/
      - .venv/

.artifacts: &artifacts_build
  artifacts:
    paths:
      - lib/frontend/static/
      - node_modules/
      - .venv/


image: kozea/python-node-yarn-postgresql:latest

install_latest:
  stage: install
  script:
    - pip install pipenv
    - make install
  <<: *artifacts_install

build_latest:
  stage: build
  script: make build
  <<: *artifacts_build
  dependencies:
    - install_latest

lint_latest:
  stage: test
  script:
    - pip install pipenv
    - make lint
  dependencies:
    - build_latest

test_latest:
  stage: test
  script:
    - pip install pipenv
    - make check
  dependencies:
    - build_latest


.image: &image_deploy_jobs
  image: kozea/deploy-tools:latest

deploy_test:
  <<: *image_deploy_jobs
  variables:
    PROJECT_NAME: ${CI_PROJECT_NAME,,}
    BRANCH_NAME: $(echo ${CI_COMMIT_RED_NAME} | tr -cd "[[:alnum:]]")
  stage: deploy_test
  script:
    - make deploy-test
  dependencies: []
  environment:
    name: test-$CI_COMMIT_REF_NAME
    url: https://test-${PROJECT_NAME}-${BRANCH_NAME}.kozea.fr

deploy_prod:
  <<: *image_deploy_jobs
  stage: deploy_prod
  script:
    - make deploy-prod
  dependencies: []
  only:
    - master
