image: paradoxxxzero/python-node-yarn-postgresql:3.5-7.2-9.6

cache:
   key: "$CI_BUILD_REF_NAME"
   untracked: true

stages:
  - install
  - build
  - test

install3.5:
  stage: install
  script:
    - make install
  artifacts:
    paths:
      - node_modules/
      - .env/

build3.5:
  stage: build
  script: make build
  artifacts:
    paths:
      - gibolt/frontend/static/
      - node_modules/
      - .env/
  dependencies:
    - install3.5

lint3.5:
  stage: test
  script: make lint
  dependencies:
    - build3.5

test3.5:
  stage: test
  script: make check
  dependencies:
    - build3.5


install_latest:
  image: paradoxxxzero/python-node-yarn-postgresql:3.6-7.5-9.6
  stage: install
  script:
    - make install
  artifacts:
    paths:
      - node_modules/
      - .env/

build_latest:
  image: paradoxxxzero/python-node-yarn-postgresql:3.6-7.5-9.6
  stage: build
  script: make build
  artifacts:
    paths:
      - gibolt/frontend/static/
      - node_modules/
      - .env/
  dependencies:
    - install_latest

lint_latest:
  image: paradoxxxzero/python-node-yarn-postgresql:3.6-7.5-9.6
  stage: test
  script: make lint
  dependencies:
    - build_latest

test_latest:
  image: paradoxxxzero/python-node-yarn-postgresql:3.6-7.5-9.6
  stage: test
  script: make check
  dependencies:
    - build_latest
