export PROJECT_NAME = gibolt
HOST=localhost
PYTHON_PORT = 1520
STATIC_PORT = 1521
RENDER_PORT = 1522

export STATIC_SERVER = http://$(HOST):$(STATIC_PORT)
export RENDER_SERVER = http://$(HOST):$(RENDER_PORT)
export FLASK_APP = $(PROJECT_NAME).backend
export FLASK_CONFIG = $(PWD)/$(PROJECT_NAME)/backend/application.cfg
export FLASK_DEBUG = 1

# Python env
VENV = $(PWD)/.env
PIP = $(VENV)/bin/pip
PYTHON = $(VENV)/bin/python
PYTEST = $(VENV)/bin/py.test
FLASK = $(VENV)/bin/flask

# Node env
NPM ?= yarn
NODE_MODULES = $(PWD)/node_modules
