"""Priority value uniqueness

Revision ID: 038289af314d
Revises: 9c7e7a199c46
Create Date: 2018-01-29 10:28:44.576212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038289af314d'
down_revision = '9c7e7a199c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priority', schema=None) as batch_op:
        batch_op.create_unique_constraint('value_unique', ['value'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priority', schema=None) as batch_op:
        batch_op.drop_constraint('value_unique', type_='unique')

    # ### end Alembic commands ###
