"""meeting value update

Revision ID: 29bd98e9bc2d
Revises: 8553c08ad953
Create Date: 2018-03-01 15:25:51.567008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29bd98e9bc2d'
down_revision = '8553c08ad953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket', sa.String(), nullable=True))

    with op.batch_alter_table('report_attendee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=True))

    with op.batch_alter_table('report_checklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item', sa.String(), nullable=True))

    with op.batch_alter_table('report_indicator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item', sa.String(), nullable=True))

    with op.batch_alter_table('report_milestone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_milestone', schema=None) as batch_op:
        batch_op.drop_column('milestone')

    with op.batch_alter_table('report_indicator', schema=None) as batch_op:
        batch_op.drop_column('item')

    with op.batch_alter_table('report_checklist', schema=None) as batch_op:
        batch_op.drop_column('item')

    with op.batch_alter_table('report_attendee', schema=None) as batch_op:
        batch_op.drop_column('user')

    with op.batch_alter_table('report_agenda', schema=None) as batch_op:
        batch_op.drop_column('ticket')

    # ### end Alembic commands ###
