"""Circle (de)activation

Revision ID: 3d7cf7c8aa4c
Revises: ce7b86aad6cd
Create Date: 2018-01-08 12:07:48.117517

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3d7cf7c8aa4c"
down_revision = "ce7b86aad6cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "circle",
        sa.Column(
            "is_active", sa.Boolean(), server_default="1", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("circle", "is_active")
    # ### end Alembic commands ###
