"""New table Label

Revision ID: 4324a085410e
Revises: 7980badc5c6f
Create Date: 2018-01-22 16:02:41.027101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4324a085410e'
down_revision = '7980badc5c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_label_id', 'label', ['label_id'], ['label_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.drop_constraint('fk_label_id', type_='foreignkey')

    # ### end Alembic commands ###
