"""delete field

Revision ID: 691f13d1880e
Revises: f6e0eb07959a
Create Date: 2018-03-09 11:15:39.447296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691f13d1880e'
down_revision = 'f6e0eb07959a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_indicator', schema=None) as batch_op:
        batch_op.drop_column('value')
        batch_op.add_column(sa.Column('value', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_indicator', schema=None) as batch_op:
        batch_op.drop_column('value')
        batch_op.add_column(sa.Column('value', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
