"""report modification

Revision ID: 7980badc5c6f
Revises: cab67e69e22c
Create Date: 2018-01-17 15:54:42.482871

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7980badc5c6f"
down_revision = "cab67e69e22c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report", sa.Column("modified_at", sa.DateTime(), nullable=True)
    )  # noqa
    op.add_column(
        "report", sa.Column("modified_by", sa.Integer(), nullable=True)
    )  # noqa
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report", "modified_by")
    op.drop_column("report", "modified_at")
    # ### end Alembic commands ###
