"""new tables Label & Priority

Revision ID: 89874856c913
Revises: 7980badc5c6f
Create Date: 2018-01-24 10:39:50.346139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89874856c913'
down_revision = '7980badc5c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'label',
        sa.Column('label_id', sa.Integer(), nullable=False),
        sa.Column('label_type', sa.Enum('circle'), nullable=True),
        sa.Column('label_name', sa.String(), nullable=True),
        sa.Column('label_color', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('label_id')
    )
    op.create_table(
        'priority',
        sa.Column('priority_id', sa.Integer(), nullable=False),
        sa.Column('label_id', sa.Integer(), nullable=False),
        sa.Column('priority_label', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['label_id'], ['label.label_id'], name='fk_priority_label'),
        sa.PrimaryKeyConstraint('priority_id')
    )
    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_circle_label', 'label', ['label_id'], ['label_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.drop_constraint('fk_circle_label', type_='foreignkey')
        batch_op.drop_column('label_id')

    op.drop_table('priority')
    op.drop_table('label')
    # ### end Alembic commands ###
