"""Role & focus 1

Revision ID: b588680b9f75
Revises: 691f13d1880e
Create Date: 2018-03-12 10:44:03.040815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b588680b9f75'
down_revision = '691f13d1880e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('role_purpose', sa.String(), nullable=True),
    sa.Column('role_domain', sa.String(), nullable=True),
    sa.Column('role_accountabilities', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circle.circle_id'], name='fk_role_circle'),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('focus',
    sa.Column('focus_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('focus_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['tmp_role.role_id'], name='fk_focus_role'),
    sa.PrimaryKeyConstraint('focus_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('focus')
    op.drop_table('tmp_role')
    # ### end Alembic commands ###
