"""add checklist field

Revision ID: f8208b71dad4
Revises: 08df6e0f01e5
Create Date: 2018-01-03 10:17:09.080459

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f8208b71dad4"
down_revision = "08df6e0f01e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role", sa.Column("role_checklist", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role", "role_checklist")
    # ### end Alembic commands ###
